language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libgeos-dev
    - python-numpy

script:
- python setup.py test
deploy:
  provider: pypi
  user: devseed
  password:
    secure: FJQuM5xRJWzTVFUbN/JOzMKD6c/CUOE6doNtS6QR1HNOp+s+o1SRs2UqYwN9tcs0b8yNor1UHLnjx4YiAWxQFCC9ReUqqzVQar0NLS0d6IY30Dlk/ZhbbArmBhj6Lyyhsp3YlF9vryii76z+h9o5W5wLcxJLnxj/xmpq++uHn81jW4ZOeyAHJ0wrZatOxu2efJQB19J+PKqZC+8Pz0rc+Xye41B0Ekt3la/Ra9cA8OUEkwkDhamCQNQQlnuElu6IWabJrYIXg23S76oRf89AjOOFTBsOn16Y+rc6hqksDdsDrVF5hUjMo43Z/HUp5oukbd3hAfuBsaKns8zAmFQmwwIW9mtDV/NsU2f19fUfXyjSSxG51gkQz47hINxFEeWY6A9XJ0hoIFCMKxwPp8Qd12EhjwWOLopquukEGL8d1AtZeX1I7UKC5fFEgBZHSm7rT8rBSwLrze9N1s+O6tbWDBAVv9tpkmmeYgdYfUvkMOjKX+J4U6ngtQm5ZOo/Otd0quXtNY+EP4B48exumvHDcoNmkSEPHBdrWDaAki7WDn96OCfSmA/DisEhPq4sdcuSdD6rMyuo/eLmYNuPHYPk6AS8ghR85eU/dstKHqpeBrw5bDIl88wKcXJzxraTzudegiVWWDNTbYtLzD24M0DRQ8z4F4Ulvw3xiKROWoG9BTI=
  on:
    distributions: sdist bdist_wheel
    repo: developmentseed/sentinel-s3
    branch: master
